spring:
  application:
    name: nextGen
  datasource:
    username: laver
    password: 7T6ZpRHDSCXYZeHB
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.199.156.222:3306/laver?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
  ai:
    openai:
      api-key: sk-57d0dd46805647d9a8aa4d38b41b759b
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      embedding:
        options:
          model: text-embedding-v3
      chat:
        options:
          model: qwen-plus
  profiles:
    active: dev

server:
  port: 8899

# 日志配置
logging:
  level:
    root: INFO
    com.example.nextgen: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"